### ISSUE TITLE
No module named 'coloredlogs'

### ISSUE THREAD

**Issue by hackison** [almandin/fuxploider#13]
![screenshot from 2018-10-29 22-13-42](https://user-images.githubusercontent.com/39798618/47665808-00503a00-dbc8-11e8-8495-0211334d1e99.png)

**Comment by hackison** [comment]
python3 fuxploider.py 
Traceback (most recent call last):
  File "fuxploider.py", line 2, in <module>
    import re,requests,argparse,logging,os,coloredlogs,datetime,getpass,tempfile,itertools,json,concurrent.futures,random
ModuleNotFoundError: No module named 'coloredlogs'

**Comment by almandin** [comment]
Did you install the required packages with `pip3 install -r requirements.txt` ?
If so, can you give me the output of the command (pip3 ...) ?

**Comment by hackison** [comment]
s i installed the requirements with pip install -r requirements.txt command pip is not working

**Comment by hackison** [comment]
![screenshot from 2018-10-30 00-40-20](https://user-images.githubusercontent.com/39798618/47674058-68108000-dbdc-11e8-8f2a-657ea5f83833.png)

**Comment by almandin** [comment]
`apt install python3-pip`

**Comment by almandin** [comment]
you may need to run pip3 as root (sudo)

**Comment by hackison** [comment]
![screenshot from 2018-10-30 01-08-25](https://user-images.githubusercontent.com/39798618/47675580-57620900-dbe0-11e8-9337-4e4fbb79afe4.png)
 Showing like this

**Comment by bc0la** [comment]
![image](https://user-images.githubusercontent.com/12816815/47686252-83659600-dbb0-11e8-9074-6fc163deb50d.png)
The error messages aren't related to installing pip. If you still can't `pip3 install -r requirements.txt`, you may need to check out this link - [https://superuser.com/questions/769920/python3-pip-installed-but-pip3-command-not-found](https://superuser.com/questions/769920/python3-pip-installed-but-pip3-command-not-found)

**Comment by hackison** [comment]
sucesfully installed thanks

**Comment by kirtiso** [comment]
Hey hackison,
i have same error No module named 'coloredlogs' 

~/fuxploider# python3 fuxploider.py -h
Traceback (most recent call last):
  File "fuxploider.py", line 12, in <module>
    import coloredlogs
ModuleNotFoundError: No module named 'coloredlogs'

and after using apt install pythpn3-pip doesn't work

root@kali-test-workstation:~/fuxploider# apt install python3-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3-pip
root@kali-test-workstation:~/fuxploider# sudo apt install python3-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3-pip

**Comment by Jerry123J** [comment]
> `python3 -m pip install -r requirements.txt`

Thanks alot bro u helped me lot

**Comment by Rygorazd** [comment]
> `python3 -m pip install -r requirements.txt`

this helped me too, thanks
