### ISSUE TITLE
templates contains utf-8, which my python3 balks at

### ISSUE THREAD

**Issue by no-boot-device** [almandin/fuxploider#19]
```
bootsy@vps:~/fuxploider$ python3 fuxploider.py
Traceback (most recent call last):
  File "fuxploider.py", line 31, in <module>
    templates = json.loads(fd.read().encode("utf-8"))
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1492: ordinal not in range(128)
```

**Comment by almandin** [comment]
It looks like 0xe2 is the character 'â'. Did you add anything to the files techniques.json or templates.json ? I don't find any 'â' in these files at the moment.

**Comment by bigjango13** [comment]
As of [a9eb7e3](https://github.com/almandin/fuxploider/commit/a9eb7e3a3cb40b36fba0365f5a49ffc68e0cac61) fuxploider uses utf-8 encoding so it should work.
