### ISSUE TITLE
Error in fuxploider.py line 12  (ImportError: No module named 'coloredlogs')

### ISSUE THREAD

**Issue by theredteamhacker** [almandin/fuxploider#30]
Traceback (most recent call last):
  File "fuxploider.py", line 12, in <module>
    import coloredlogs
ImportError: No module named 'coloredlogs'

**Comment by EmreOvunc** [comment]
> I got the following error when I run the fuxploider.py file
> 
> Traceback (most recent call last):
> File "fuxploider.py", line 12, in 
> import coloredlogs
> ImportError: No module named 'coloredlogs'

You can install this module:
```
pip3 install coloredlogs
```

**Comment by almandin** [comment]
you can also try `python3 -m pip install coloredlogs` if the previous answer doesnt work.

**Comment by bigjango13** [comment]
Fixed by [c5f25de](https://github.com/almandin/fuxploider/commit/c5f25de99f64e246e18c33cb04db0d2de3112852).
