### ISSUE TITLE
AttributeError: 'str' object has no attribute 'text'

### ISSUE THREAD

**Issue by inj3ctor-m4** [almandin/fuxploider#32]
when i accepte uploading payloads 

after uploading nearly 50 file then an error message occurs:

Traceback (most recent call last):
  File "fuxploider.py", line 371, in <module>
    res = future.result()
  File "C:\Users\p4rola\Anaconda3\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "C:\Users\p4rola\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\p4rola\Anaconda3\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Pentest\fuxploider\UploadForm.py", line 258, in submitTestCase
    url = f"{self.schema}://{self.host}/{self.uploadsFolder}/{fu[1].text}"
AttributeError: 'str' object has no attribute 'text'

**Comment by pandasauce** [comment]
This seems to be because `submitTestCase()` expects the output of `uploadFile()` to contain sometimes HTML nodes and sometimes strings at index `1`. Yay dynamic typing.

A *very* dirty hack just to get it to work would be:

```diff
diff --git a/UploadForm.py b/UploadForm.py
index 537c885..63305df 100644
--- a/UploadForm.py
+++ b/UploadForm.py
@@ -250,13 +250,14 @@ class UploadForm:
             url = None
             secondUrl = None
             if self.uploadsFolder or codeExecURL:
+                fu1 = (fu[1] if isinstance(fu[1], str) else fu[1].text)
                 if codeExecURL:
                     filename_wo_ext = fu[2]
                     url = codeExecURL.replace("$uploadFormDir$", os.path.dirname(self.uploadUrl)) \
                                      .replace("$filename$", filename_wo_ext)
                 else:
-                    url = f"{self.schema}://{self.host}/{self.uploadsFolder}/{fu[1].text}"
-                filename = fu[1].text
+                    url = f"{self.schema}://{self.host}/{self.uploadsFolder}/{fu1}"
+                filename = fu1
                 secondUrl = None
                 for byte in getPoisoningBytes():
                     if byte in filename:
```

But a proper solution would ensure the `.text` conversion happens before calling `submitTestCase()`.

**Comment by BoboTiG** [comment]
Fixed with 2c614e37eb16af1c86ce06c1e2448ad82bef16f, I guess.
