### ISSUE TITLE
I can't seem to get it working

### ISSUE THREAD

**Issue by meshari10** [almandin/fuxploider#36]
Traceback (most recent call last):
  File "fuxploider.py", line 15, in <module>
    from utils import *
  File "/root/Desktop/fuxploider/utils.py", line 9, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python3.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python3.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python3.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'

**Comment by Die-Mannschaft** [comment]
same problems here as mentioned bt @meshari10

**Comment by waall** [comment]
Maybe, fuxploider.py is not in the same directory as the libs, try to execute python3 fuxploider.py where it was installed
